#block[
#block[
== A taxonomy of service identification approaches for legacy software systems modernization

#block(fill: rgb("f8f9fa"), inset: 8pt, radius: 3pt, width: 100%)[
  #text(size: 0.9em)[*Source:* M. Abdellatif _et al._ "A taxonomy of service identification approaches for legacy software systems modernization," _Journal of Systems and Software_, 2021. [Online]. Available: #link("https://linkinghub.elsevier.com/retrieve/pii/S0164121220302582")]
]

#block(fill: rgb("f8f9fa"), inset: 8pt, radius: 3pt, width: 100%)[
  #text(size: 0.9em)[*Paper Information:* Systematic Literature Review (SLR)]
]

#block(fill: rgb("f8f9fa"), inset: 8pt, radius: 3pt, width: 100%)[
  #text(size: 0.9em)[*Rating:* ⭐⭐⭐⭐ (4\/5)]
]

#block(fill: rgb("f8f9fa"), inset: 8pt, radius: 3pt, width: 100%)[
  #text(size: 0.9em)[*Own Keywords:* Background, Analysis of Service Identification Approaches (SIA), Migration, SIA Taxonomy]
]

#block(fill: rgb("f8f9fa"), inset: 8pt, radius: 3pt, width: 100%)[
  #text(size: 0.9em)[*Reading Progress:* Second Pass]
]

== Introduction (What is the Paper about?)

- Paper #strong[performed an SLR] to #strong[create a taxonomy] to
  categorize #emph[Service Identification Approaches (SIA)] focusiing on
  #emph[bottom-up] and #emph[hybrid strategies]
- Paper aims to study SIAs in literature along four dimensions:
  #emph[Used Inputs], #emph[Applied Processes], #emph[Resulting Outputs]
  and #emph[Usability Degree]
- #strong[Goal:] #strong[Help Practitioners in selecting a suitable SIA]

== Methods

- SLR covering 41 published SIAs (retained from a first set of 3,246
  Papers) based on software-systems analyses
  - #strong[build SLR based on own experience] with migration and
    experiences working in industry
  - focusing on #emph[bottom-up] and #emph[hybrid] approaches that rely
    on existing software artifacts
  - #strong[Reason:] Studies and experience have shown that companies
    often only have source code as most up-to-date source of information
    about their legacy systems
    - #emph[\(Comment)] Missing requirement engineering data and
      artifacts during the software designing process are hindering a
      #emph[top-up] approach ?
- #strong[Validation of correctness and coverage] through a
  #strong[survey] and #strong[one-to-one interviews] with 45
  #strong[industrial experts] who are performing migration

== Scientific Benefit

- #strong[Taxonomy to categorize #emph[Service Identification Approaches
  (SIA)]]
  - Build a multi-layer classification starting from high-level, based
    on #emph[Used Inputs], #emph[Applied Processes], #emph[Given
    Outputs] and the #emph[SIAs Usability]
  -
- #strong[Most existing SIAs look for services based on functional
  cohesion and low coupling towards other parts of the applications]
  - disregard service types
  - current trend is to identify microservices by applying the same
    techniques used for identifying “normal” services
- #strong[Results show that classification suits industrial experts'
  experience]
  - Precision of 99% and a recall of 94%

== Challenges / Future Work

- #strong[Most studied SIAs are still at their infancy]
  - #emph[\(Comment)] May be potentially outdated
  - lack of validation on real enterprise-scale systems
  - lack of tool support
  - lack of automation of SIAs
  - lack of quality assessment of the identified services
- #strong[SIAs generally ignore economic aspects] like
  #emph[implementation], #emph[maintenance], #emph[re-factoring costs
  and time-to-market issues]
  - only a few SIAs consider economic aspects
- #strong[SIAs should provide means to assess their quality and consider
  economic aspects]
- #strong[Authors are convinced that] #strong[more work should be done
  to automate] state-of-the-art SIAs
- #strong[Granularity between services and microservices is still not
  well defined] nor clearly discussed by SIA approaches

== Limitations

== Paper Outline and Read Progress

+ \[X\] Introduction
+ \[X\] SLR Methodology
+ \[X\] Inputs used by SIAs
+ \[ ~\] Applied Processes
+ \[ ~\] Outputs generated by SIAs
+ \[ ~\] Usability Level of these SIAs
+ \[ ~\] Validation of the taxonomy
+ \[X\] Comparison between studied SIAs
+ \[X\] Related Work
+ \[X\] Conclusion

== Own Comments

- \(+) Key Paper
- \(-) Potential subjective because the authors mentioned they build
  their SLR based on their own experience
]
]